### ISSUE TITLE
Is it too soon to use the new API?

### ISSUE THREAD

**Issue by georgefst** [monadicsystems/okapi#30]
I really like the idea of Okapi, as I usually find myself wanting something more type-safe than Scotty, but easier to work with than Servant.

Unfortunately, version 0.1 on Hackage is basically unusable because of the way things are constantly dumped to stdout. Plus, there's little documentation, and what there is contains broken links and examples which don't compile. But it is a version 0.1, and you've mentioned that it's an early and experimental release, so that's fine!

What I'm curious about is that [the wiki](https://okapi.wiki) describes a very different API, as mentioned in [your Reddit post](https://www.reddit.com/r/haskell/comments/12u01wg/okapi_from_monad_to_applicative/), which looks like a great improvement (the overall idea anyway - I could quibble about minor things like having to import so much qualified). But it's not clear whether it's even possible to use it yet. The examples don't compile with the current main branch, and there are other newer branches floating around, which mostly don't build at all.

So, is there a commit anywhere with which it is possible to use the new API, or do we just need to wait for things to stabilise? I'm using 0.1 for now on a small, low-stakes personal project, so I really don't mind breaking changes or the occasional bug, and I'd be happy to act as a sort of beta tester.

**Comment by rashadg1030** [comment]
@georgefst Sorry for the late reply. Please do not use for anything serious yet. A better API is in the works with new docs and everything.

**Comment by rashadg1030** [comment]
@georgefst May you join the Discord server I've created [here](https://discord.gg/3jGms3F5)? I'd like to have others begin using the latest version of Okapi. I'm planning on releasing this version to Hackage soon once I iron out a few more things. Before I do that, I'd like some feedback.

**Comment by georgefst** [comment]
Just joined! I'm going to be very busy across the next two weeks, but then I'll be off work for a while and spending a lot of time on open source stuff. So if you haven't released by then, I can certainly help with testing.

**Comment by rashadg1030** [comment]
@georgefst Sounds good! Looking forward to it.
