### ISSUE TITLE
Small typo in the introduction

### ISSUE THREAD

**Issue by kfl** [monadicsystems/okapi#5]
The introduction has the following example:

```haskell
greet = do
  seg "greet"
  name <- pathParam
  returnPlainText [] $ "Hello " <> name <> "! I'm Okapi."
```

And say that this will set up a server that listens to `http://localhost:3000/greeting/Bob`.

I think that either should `seg "greet"` be changed to `seg "greeting"` or the URL should be changed to `http://localhost:3000/greet/Bob`.

**Comment by rashadg1030** [comment]
@kfl Thank you for noticing. I believe this is fixed, but the documentation is changing anyway.
