### ISSUE TITLE
The "Edit this page on GitHub links does not work"

### ISSUE THREAD

**Issue by kfl** [MonadicSystems/okapi#6]
Each page in the [documentation](https://www.okapi.wiki/) has an `Edit this page on GitHub` link. However these links direct you to the non-existent (or private) repo <https://github.com/MonadicSystems/okapi-docs>.

**Comment by rashadg1030** [comment]
@kfl I believe I fixed this sometime ago, thank you for the notice and sorry for the late reply... stay tuned as more features are being released very soon.
